### ISSUE TITLE
Support Channel Praise Sponsor Suggest Add Tag

### ISSUE THREAD

**Issue by aa1008611** [ariadata/mtproxy#1]
Support Channel Praise Sponsor Suggest Add Tag

**Comment by pcmehrdad** [comment]
Thank you for your suggestion to support Channel Praise Sponsor Suggest Add Tag. I understand that this is a feature that would be useful for many users.
Unfortunately, this is a customized version of MTProxy that I use for personal use. I don't have the time or resources to upgrade it to support this feature.
I apologize for any inconvenience this may cause. I will keep your suggestion in mind if I ever have the opportunity to upgrade MTProxy in the future.

**Comment by aa1008611** [comment]
Think you
